version: '3.1'
services:
  hello:
    image: hello-img
    profiles: ["apps"]
    build: .
    ports:
      - 8080:8080
    environment:
      ENVIRONMENT_NAME: local
      MONGODB_CONECTION_URL: mongodb://root:example@mongo:27017/
    restart: always
  mongo:
    image: mongo:5.0.2
    profiles: ["apps"]
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-admin-ui:
    image: mongo-express
    profiles: ["apps"]
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    profiles: [ "monitoring" ]
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
  prometheus:
    image: prom/prometheus:v2.33.4
    profiles: ["monitoring"]
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/etc/prometheus/durable"
    ports:
      - 9090:9090
  alertmanager:
    image: prom/alertmanager:v0.23.0
    profiles: [ "monitoring" ]
    volumes:
      - ./monitoring/alertmanager/:/config/
    command: --config.file=/config/alertmanager.yml --log.level=debug
    ports:
      - "9093:9093"
  grafana:
    image: grafana/grafana:8.4.3
    profiles: ["monitoring"]
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  wrk-injector-hello-functional:
    image: mtchavez/docker-wrk
    command: wrk -t4 -c10 -d300s http://host.docker.internal:8080/hello-world
  wrk-injector-info-perf:
    image: mtchavez/docker-wrk
    command: wrk -t4 -c1000 -d5m --timeout 1s --latency http://host.docker.internal:8080/info
